### ISSUE TITLE
Segfault on Ubuntu 18.10

### ISSUE THREAD

**Issue by hypnomaki** [ehrishirajsharma/SwiftnessX#15]
When starting, it just segfaults. 
Perhaps because of node library not being compatible to glibc?

See:

- https://github.com/electron/electron/issues/13972

- https://stackoverflow.com/questions/53084955/why-does-slack-return-a-segmentation-fault-after-fedora-29-upgrade/53084956?noredirect=1#comment93330154_53084956

**Comment by ehrishirajsharma** [comment]
This is fixed in latest release, please confirm.

**Comment by hypnomaki** [comment]
It now works as expected on Ubuntu 18.10
Thank you!
