### ISSUE TITLE
Font size, code block,color, and keyboard shortcut

### ISSUE THREAD

**Issue by iNoSec** [ehrishirajsharma/SwiftnessX#16]
Hello and thanks for your tool!!!

Can you implement font size choice and other stuff related to, like unorder list, center, etc, implementing a code block like cherrytree, possibility to have some keyboard shortcut for copy/paste from clipboard, it is useful for images like keepnote/cherrytree, implementing the possibility to include videos locally. 

I know i ask a lot :p

**Comment by ehrishirajsharma** [comment]
Thanks @iNoSec 

Yes, we are working on all of the above mentioned things. You can also track few of them on #1, #2  and #3 

I will update this thread once these are available.
