### ISSUE TITLE
Highlight the search results to the right

### ISSUE THREAD

**Issue by dd404x** [ehrishirajsharma/SwiftnessX#17]
Highlight the search results to the right
![image](https://user-images.githubusercontent.com/19923974/49498190-3064ba00-f8a5-11e8-8fd6-052fac39d934.png)

**Comment by ehrishirajsharma** [comment]
**Fixed with:** https://github.com/ehrishirajsharma/SwiftnessX/commit/a0480195054ba0f1cab3a24a3e2c76ceeade8a48
