### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by sieunhando** [ehrishirajsharma/SwiftnessX#18]
Thanks.

**Comment by GouveaHeitor** [comment]
@ehrishirajsharma any update?

**Comment by ehrishirajsharma** [comment]
Hi @GouveaHeitor,

It will be released along with v0.2. I will update this issue once its ready.

**Comment by ehrishirajsharma** [comment]
Hi @sieunhando  and @GouveaHeitor,

Please check the macOS package: https://github.com/ehrishirajsharma/SwiftnessX/releases/download/v0.2.0/SwiftnessX.zip

Please let me know if it is working as expected.
