### ISSUE TITLE
Image Manipulation Support

### ISSUE THREAD

**Issue by wildkindcc** [ehrishirajsharma/SwiftnessX#2]
The current image processing of the application can be difficult to fit into workflows promoted by other note taking applications, ie OneNote, KeepNote, etc.

Allowing the ability to copy in images from the user's clipboard, storing them within the exported .json file and allowing basic image manipulation (Resize to percentage of original, resize to specific pixel size, etc) would facilitate storing testing evidence within the application.

**Comment by ehrishirajsharma** [comment]
Hi @wildkindcc,

This has been fixed with the [latest release](https://github.com/ehrishirajsharma/SwiftnessX/releases/tag/v0.2.0). Please confirm if it is working as expected.

**Source:** https://github.com/ehrishirajsharma/SwiftnessX/commit/b2c4bcd61e371027ea6276d7f436e510436fc67c
