### ISSUE TITLE
Checkbox/completed symbol

### ISSUE THREAD

**Issue by SolomonSklash** [ehrishirajsharma/SwiftnessX#20]
It would be useful to be able to make checkboxes, similar to [Markdown checkboxes](https://github.com/westurner/wiki/wiki/Checkboxes--markdown), within notes. This would be especially helpful in the template section, as a way to visually verify certain steps or processes have been completed.

**Comment by ehrishirajsharma** [comment]
Hi @SolomonSklash,

It is included in the [latest release](https://github.com/ehrishirajsharma/SwiftnessX/releases/tag/v0.2.0). Could you please confirm it if it is working as expected?


To check the source:https://github.com/ehrishirajsharma/SwiftnessX/commit/18e61633d8b7d0f05c5633ea45d1af6fd1a92532
