### ISSUE TITLE
How to import/export my payloads and other stuff to file and then read them to the swiftness?

### ISSUE THREAD

**Issue by marataziat** [ehrishirajsharma/SwiftnessX#22]
Where is swiftness stores database files to move them?

**Comment by ehrishirajsharma** [comment]
You can import/export the SwiftnessX compatible JSON file from the bottom left option (next to logo).

Regarding the database file, please let me know your operating system.

**Comment by ashhadali10** [comment]
when i export it give me error something went wrong mt OS is parrot 4.7
