### ISSUE TITLE
Open-source Penetration Testing Checklists

### ISSUE THREAD

**Issue by 007divyachawla** [ehrishirajsharma/SwiftnessX#23]
Operating System: Windows 8 (64 Bit)

**Describe the bug**
Unable to see the Pre-built Checklist in the Library Section

**To Reproduce**
Install the Windows Swiftness and then Click on the Swuftness App.
In the Libraries section, check for the Prebuilt Checklist.

**Expected behavior**
Prebuilt Checklist should be present in the Window installation.

**Screenshots**
Screenshot added.

**Additional context**

![image](https://user-images.githubusercontent.com/7563150/51095705-a6313f00-17dc-11e9-80b7-c57171cf6c12.png)

**Comment by 007divyachawla** [comment]
![image](https://user-images.githubusercontent.com/7563150/51095750-fc05e700-17dc-11e9-9388-a13c6acbd5c0.png)

**Comment by 007divyachawla** [comment]
In the first image cannot see the Checklist(Pre-built), but in the second image which i have taken from the Github video able to see the Checklist PreBuilt.

**Comment by hbenaissa** [comment]
i have the same issue on Windows 7

**Comment by ehrishirajsharma** [comment]
* **RE Windows 8/7 Support:** I am not sure about the prior versions of Windows 10 however, I will check and confirm it very soon.

* **RE Prebuilt Checklist**: @007divyachawla, It's currently not available by default in Electron version. I am currently working on multiple checklists along with few security-researchers, I will update here when it is ready.

**Comment by 007divyachawla** [comment]
@ehrishirajsharma Thanks Bro, could you please share the checklist so that we add it manually. Its a great tool.

**Comment by 007divyachawla** [comment]
@ehrishirajsharma I have installed the same in Mac but still unable to see the Prechecklist option, please look into the same

**Comment by zeeshan-csr** [comment]
@ehrishirajsharma Same issue with me on Windows 8.1. That would be really great if you can provide the checklist so that we can add it manually. Thanks in advance!

**Comment by 007divyachawla** [comment]
@ehrishirajsharma  Any update on this.

**Comment by ehrishirajsharma** [comment]
Hi @zeeshan-csr and @007divyachawla,

This repository doesn't have in-built checklist. I am aiming to include this with `v0.3` release.

**Comment by sawzeeyy** [comment]
You're doing a great work @ehrishirajsharma. TYVM 🤙

**Comment by ehrishirajsharma** [comment]
Hi,

You can download the checklists (aiming to release few more by `v0.3`, especially around `bug-bounty`):
https://github.com/ehrishirajsharma/swiftness-static/tree/master/Checklist

To contribute, please request for the **private-repo** here: https://forms.gle/7W4SQJJjwuNLPESV6
