### ISSUE TITLE
Segfault when running swiftness-0.2.0-x86_64.AppImage 

### ISSUE THREAD

**Issue by SolomonSklash** [ehrishirajsharma/SwiftnessX#29]
Operating System: Latest Kali Linux

**Describe the bug**
After making the `swiftness-0.2.0-x86_64.AppImage` file executable and running it, clicking yes to the prompt to integrate with the operating system, I get a segmentation fault error, with no other details.

**To Reproduce**
1. Download `swiftness-0.2.0-x86_64.AppImage`
2. `chmod +x swiftness-0.2.0-x86_64.AppImage`
3. Run with `./swiftness-0.2.0-x86_64.AppImage`
4. Click yes to system integration prompt.
5. Get segfault error.

**Comment by ehrishirajsharma** [comment]
Thanks @SolomonSklash. Is previous version working perfectly in the same environment?

**Comment by ehrishirajsharma** [comment]
Thanks @SolomonSklash. I forgot to confirm it on Kali Linux, does earlier version work as expected in this same environment?

**Comment by SolomonSklash** [comment]
Yep, the previous one works just fine.

**Comment by ehrishirajsharma** [comment]
Okay. I am on it, will get back to you when I found the root-cause.

**Comment by Gon-Freecss-hunter** [comment]
Hi, I had the same problem with the new version of ubuntu 19.04.

**Comment by ehrishirajsharma** [comment]
Hi @SolomonSklash and @Gon-Freecss-hunter, 

Can you please retest with the latest release? It should be fixed now.

**Comment by SolomonSklash** [comment]
Works for me. Thanks!
