### ISSUE TITLE
Highlighting for Targets, Checklists, Notes and Lines of Text

### ISSUE THREAD

**Issue by wildkindcc** [ehrishirajsharma/SwiftnessX#3]
Implementation of some form of highlighting within the various windows will allow for an at-a-glance look at notes.  This will be useful for keeping track of areas where there are significant issues, things an application may do well, or important bits of information.

In addition, depending on workflows, this can also facilitate peer reviews of testing engagements, allowing the reviewer to quickly familiarise themselves with areas within the notes which they may need to pay specific attention.

Similar functionality exists within the "KeepNote" application, allowing highlighting of Items, subitems and text within stored notes.  See images below for example:

![image](https://user-images.githubusercontent.com/25321621/48328155-e10cde80-e696-11e8-9e74-908814b0e8c2.png)

![image](https://user-images.githubusercontent.com/25321621/48328200-292c0100-e697-11e8-861e-92dce96e13d7.png)

**Comment by ehrishirajsharma** [comment]
That's a great point, I will get back to you with design to confirm it. 

Thanks again,

**Comment by ehrishirajsharma** [comment]
Should we give users a limited number of possibly best colours as a choice? or a colour picker to decide it?

**Comment by BradBeacham** [comment]
A colour picker retaining several options saved in the .json would probably give the best flexibility.  Not sure on the difficulty between implementing either though.

**Comment by ehrishirajsharma** [comment]
Hi @wildkindcc, 

It's done in the latest version: 

<img src="https://github.com/ehrishirajsharma/swiftness-static/raw/master/Assets/main-view.png" 
 align="left" width="700px"/>

- Inline text: https://github.com/ehrishirajsharma/SwiftnessX/commit/697f2705afc3099457a63a7581b6b07b4291c72d

- Targetets, Libraries, Notes and Checklist: https://github.com/ehrishirajsharma/SwiftnessX/commit/9f8d2482d9db10d808c808208c9752448d91d7a5


Please check and confirm this.
