### ISSUE TITLE
Can't Scroll on Checklist

### ISSUE THREAD

**Issue by awesomeaakash** [ehrishirajsharma/SwiftnessX#33]
When I added checklists and want to add more i see i can't scroll down 
 
![Screenshot from 2019-04-23 08-33-27](https://user-images.githubusercontent.com/8490836/56550263-cc683700-65a2-11e9-93e2-3d2b6434bb8b.png)

**Comment by ehrishirajsharma** [comment]
Strange, can you also send me the exact OS and its version? Let me try to reproduce it.

**Comment by awesomeaakash** [comment]
OS -> Ubuntu 18.04.1

What i need to is click on New+ button several times only then i able to see things and scroll things
same in text section

Plus it will be good if in text section i see some color variations like change color of text and even background page plus some more enhancements in text sections

**Comment by ehrishirajsharma** [comment]
Closing this against #42
