### ISSUE TITLE
[macOS] "Something went wrong" when exporting

### ISSUE THREAD

**Issue by pcastagnaro** [ehrishirajsharma/SwiftnessX#48]
Operating System: macOS Mojave

**Describe the bug**
When I create a library and then I try to export them, I get the message "Something went wrong" and the exported file doesn't create.

**To Reproduce**
1. Go to 'Arrow Up & Down'
2. Select the library you want to export
3. Click on 'Export'
4. Select a filename
5. See the error

![image](https://user-images.githubusercontent.com/8824742/61175807-f7ec3380-a58b-11e9-9930-6754ba4b54b8.png)

![image](https://user-images.githubusercontent.com/8824742/61175781-890eda80-a58b-11e9-9a8e-d26b2679be36.png)

**Expected behavior**
A JSON file created with the Library data

**Comment by ehrishirajsharma** [comment]
Thanks @pcastagnaro for reporting this. I was able to reproduce this in `Mojave 10.14.1` but not in latest version of `Mojave 10.14.5`, it was working as expected.

Can you also let me know your version?

**Comment by pcastagnaro** [comment]
Hi! Thanks for asking!

I have the latest version, the 10.14.5. And the most striking is that this
error happens in my first project. I don't want to do a fresh install
because I write some information in this project and I don't want to loose
them.

**Comment by ehrishirajsharma** [comment]
Don't worry, you won't loose any data (because app points a single storage file). Just keep the app open till I find a fix for this. 

In meantime you can go and save a copy of master file:

`/Users/<username>/Library/Application Support/Swiftness/storage`

(you should see a `content.json`)

**Comment by pcastagnaro** [comment]
Oh, great!
Many many many thanks! I will be expectant to the fix!

Thanks a lot again for the application and for your support!

**Comment by mpgn** [comment]
Ok guys, I locate the problem, it's linked to this call:  
https://github.com/ehrishirajsharma/SwiftnessX/blob/7e47c8de9c59547597dabd9786629dcac2e05692/app/components/ExportDialog.js#L117

`fs.writeFile` need a callback as a third parameter. You can use this dirty fix to solve the issue:

```javascript
fs.writeFile(fileName, JSON.stringify(this.state), function (err, result) {
       if (err) console.log('error', err);
});
```

**Comment by ehrishirajsharma** [comment]
Thanks @mpgn!

I am pushing this hot-fix for now, will look into the problem with `v0.3 release`.

**Comment by pcastagnaro** [comment]
Hi @ehrishirajsharma,

Could you release the `v0.3` version?

**Comment by ehrishirajsharma** [comment]
Hi @pcastagnaro,

`v0.3` is almost ready, we are aiming to release it within this month. We were a bit inactive last month.

In meantime, please check the latest release to fix this issue: https://github.com/ehrishirajsharma/SwiftnessX/releases/tag/v0.2.3

Please let me know if this fixes the current issue.

**Comment by pcastagnaro** [comment]
Thanks a lot @ehrishirajsharma!! 
It works perfect!!
