### ISSUE TITLE
No import button

### ISSUE THREAD

**Issue by condor-webdev** [ehrishirajsharma/SwiftnessX#66]
Operating System: 
Arch Linux
![image](https://user-images.githubusercontent.com/31829929/74646546-5f014480-517a-11ea-846c-c34bc1c79688.png)

**Describe the bug**
No import button appearing

**To Reproduce**
1. Launch app

**Expected behavior**
The import button should be there

**Screenshots**
![image](https://user-images.githubusercontent.com/31829929/74646475-3bd69500-517a-11ea-9bcc-ce1e9aa44088.png)

**Comment by n0sandb0x** [comment]
Button is there bro i also having the same issue but you need to somehow manage to get to the bottom of the application to see it it's right next to the logo

**Comment by condor-webdev** [comment]
Ok, thanks, i needed to switch to fullscreen to see it.
