### ISSUE TITLE
Ability to re-order Targets,  Libraries, and folders

### ISSUE THREAD

**Issue by SolomonSklash** [ehrishirajsharma/SwiftnessX#7]
It would be nice to be able to re-order Targets, Libraries, and folders. Currently they are fixed in the order that they are created and cannot be moved. The ability to sort them, alphabetically or otherwise, could be good too.

**Comment by ehrishirajsharma** [comment]
**Fixed in:** https://github.com/ehrishirajsharma/SwiftnessX/commit/66f53a0acfa2f16c0c88da165b6346f5b63a16f3
