### ISSUE TITLE
Folder "disappears" when given no name/name is deleted or empty

### ISSUE THREAD

**Issue by bellma101** [ehrishirajsharma/SwiftnessX#9]
A folder "disappears" when you delete its name. The only way to delete it is to delete its parent Target or Library.

To reproduce:
* Create a Target or Library.
* Click the new Target or Library
* Rename the folder to nothing, i.e. delete all the text.
* Notice that the folder is unable to be clicked, renamed, or deleted.

![image](https://user-images.githubusercontent.com/43149956/48329723-8bd9ba00-e60f-11e8-843b-c805d253c01b.png)

**Comment by ehrishirajsharma** [comment]
Thanks again @bellma101 for these issues, really appriciate it.

**Comment by dd404x** [comment]
![image](https://user-images.githubusercontent.com/19923974/48395089-fe9e7e80-e750-11e8-8579-49b9e654a8fb.png)
I can't delete and rename this empty name either.

**Comment by ehrishirajsharma** [comment]
This is fixed in latest release, now when you hit enter with no value its value get changed to New Library/New Checklist, etc

Please confirm, app-has auto updating system - just reopen the app twice.
